apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-server-deployment
  labels:
    app: sample-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-server
  template:
    metadata:
      labels:
        app: sample-server
    spec:
      containers:
      - name: sample-server
        image: fhilf/sample-server:1.0.0
        ports:
        - containerPort: 5000
        # env:
        # - name: USER_NAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: mongo-user
        # - name: USER_PWD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: mongo-password 
        # - name: DB_URL
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mongo-config
        #       key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: sample-server-service
spec:
  type: NodePort
  selector:
    app: sample-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100